Vagrant.configure("2") do |config|
  config.vm.box = "xolens/linux-mint-20-3"
  config.vm.box_version = "0.1.0"
  
  config.vm.provider :virtualbox do |v|
    v.gui = false
    v.memory = 4096
  end
  
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox", disabbled: true

end